language: node_js
node_js:
  - "6.10"

env:
  global:
    - CI=true

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

test:
  script:
    - npm test

script:
  - npm run-script build

deploy:
  provider: s3
  local_dir: build
  detect_encoding: true
  skip_cleanup: true
  on:
    branch: master

